### ISSUE TITLE
Fails to init with remote backend with unclear reason

### ISSUE THREAD

**Issue by jspawar** [hashicorp/setup-terraform#127]
Using the action to do a simple `terraform init` with plan as such:

```yaml
steps:
- uses: hashicorp/setup-terraform@v1
  with:
    cli_config_credentials_hostname: <terraform_enterprise_host>
    cli_config_credentials_token: <some_token>
- run: terraform init
```

The `terraform init`, which I have confirmed works on multiple different machines and of course the remote plans are still working, fails with the following output:

```
Initializing modules...
- <module> in <some_path>

Initializing the backend...

Successfully configured the backend "remote"! Terraform will automatically
use this backend unless the backend configuration changes.
Error loading state: Error creating workspace <remote_workspace_name>: resource not found
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

Not sure what I'm missing or misconfiguring. If the authentication stuff is indeed setup correctly, this is basically exactly what I've been doing on my local machines. Not sure why it claims to be creating a workspace either?

I tried setting `TF_WORKSPACE` as well to which it responded by still failing with the message: `workspaces not supported` which is confusing me even more then why it's saying `Error creating workspace` when I run without the variable set.

**Comment by cmartinez85** [comment]
Did you find a solution for this? I'm experiencing the same issue

**Comment by wallacepf** [comment]
Same here

**Comment by sharon-tickell** [comment]
I found this thread while attempting to debug the same situation (getting "Error loading state: Error creating workspace <remote_workspace_name>: resource not found" when running "terraform init")

It turned out that the problem was the access token my automation pipeline was using:  the Terraform Organization Team it was associated with didn't have the required permissions.    Once I tried a different token associated with a more privileged Team, I was able to initialize without any further problems (and also without needing to make any other changes to my pipeline configuration).    

Posting here in case that solution also works for someone else who encounters this error message.

**Comment by bflad** [comment]
Hi folks 👋 Thank you for reporting this confusing error and sorry for the trouble. Please note that error messaging from running Terraform commands, after this GitHub Action installs Terraform, is handled upstream in Terraform itself. If you are still running into a confusing error from a Terraform command, please raise a bug report upstream: https://github.com/hashicorp/terraform/issues
