### ISSUE TITLE
action in container

### ISSUE THREAD

**Issue by daroga0002** [hashicorp/setup-terraform#13]
I want to start discussion about dockerizing this action. Currently this is running on runner context and it is running fine on GitHub hosted runners, issues incoming when we want to use self hosted runners, then some strict dependencies like NodeJS and etc are causing issues.

I know that those dependencies are available under:
https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md

but this is huge list of software which we really dont want to install on our self hosted runners.

As per me best pattern for `lightweight` actions should be putting them in self-contained container.

Good example of such dockerized actions is https://github.com/Dirrk/terraform-docs where all dependencies are contained in container so self runner require just a docker to handle it.

This is not really issue, but rather proposal of changing architecture of this action to make it more available and remove 3rd party dependencies on runners.

**Comment by sudomateo** [comment]
Hello! We actually moved away from a Docker based action due to a few limitations with it. Namely, the inability to prepare the environment before executing Terraform (installing 3rd party software, etc).

The Terraform team does publish official Docker images that you may use within GitHub Actions. Perhaps that could work for your use case?

**Comment by daroga0002** [comment]
I will check, thx. Closing this issue as seems this is intentional direction.
