### ISSUE TITLE
Unable to extract value

### ISSUE THREAD

**Issue by iaacautomation** [hashicorp/setup-terraform#151]
I want to analyse the value inside the output of terraform 

      - name: Terraform Plan
        id: tf-outputs
        run: terraform output

      - name: debug
        run: |
          echo $(jq -r '.vpc' << ${{ fromJSON(steps.tf-outputs.outputs.stdout) }})

But the output doesnt not let itself be used as a input for detailed analysis. Any suggestions how to handle the output after using the action itself

**Comment by officel** [comment]
use `-json` ?
https://developer.hashicorp.com/terraform/cli/commands/output

**Comment by austinvalle** [comment]
Closing out old issues, but this one should be achievable as @officel mentioned by using the `-json` flag. There are some [examples](https://github.com/hashicorp/setup-terraform/blob/4dff81de7e5d5b20569d58e210da292d57815d51/.github/workflows/setup-terraform.yml#L308-L372) in our tests you could reference (but you could use a step output as well, if you'd like)

If you were using the wrapper for `setup-terraform` you might have had issues with invalid STDOUT, but that will be fixed in a `v3.0.0` release next. See this comment for more info on that: https://github.com/hashicorp/setup-terraform/issues/167#issuecomment-1783310845
