### ISSUE TITLE
Setup via assuming a role? 

### ISSUE THREAD

**Issue by kaihendry** [hashicorp/setup-terraform#157]
Is it possible to use a role to assume to setup AWS credentials?

* https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions#examples

For example what I do here: https://github.com/kaihendry/singapore-postcode-api/blob/master/.github/workflows/sam-pipeline.yml#L25-L28

**Comment by bflad** [comment]
Hi @kaihendry  👋 Thank you for raising this. Please note that this GitHub repository's issue tracker is only used for feature requests and bug reports for the `setup-terraform` GitHub action itself. Since this appears to be a Terraform usage question, my best recommendation would be to submit a topic in the [Terraform section of HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-core/27), where there are many more people asking and answering usage questions such as these. In general though, using configure-aws-credentials to handle AWS credentials via assuming a role, using setup-terraform to install Terraform, then calling Terraform commands that rely on the Terraform S3 backend or AWS provider should work as expected.
