### ISSUE TITLE
Request: Support PowerShell

### ISSUE THREAD

**Issue by ja-nick** [hashicorp/setup-terraform#198]
PowerShell is a great alternative to bash if you need to do any data munging or write scripts longer than a few lines. Is there anything that makes supporting PowerShell difficult for those use cases?

**Comment by jpogran** [comment]
@ja-nick is there an example of using this action with a `pwsh` shell that isn't working? I can investigate which part of this action isn't setup to work with PowerShell if I have something to test against

**Comment by bflad** [comment]
Closing due to lack of response. Please note that this GitHub repository's issue tracker is only used for feature requests and bug reports for the `setup-terraform` GitHub action itself. If you are still running into trouble, my best recommendation would be to submit a topic in the [Terraform section of HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-core/27), where there are many more people asking and answering usage questions such as these.
