### ISSUE TITLE
Remove double-quotes around "main" branch in terraform.yml workflow template

### ISSUE THREAD

**Issue by kjjames** [hashicorp/setup-terraform#213]
### Steps to reproduce:
<img width="1264" alt="Screen Shot 2022-06-09 at 3 52 46 PM" src="https://user-images.githubusercontent.com/25905289/172933409-df4b596e-c911-4dfd-b16c-3f1174e8ae3b.png">  
<img width="868" alt="Screen Shot 2022-06-09 at 3 53 39 PM" src="https://user-images.githubusercontent.com/25905289/172933444-01ea69a8-73aa-481b-b279-4392073a005b.png">  

Example:  
`terraform apply` step is skipped in the workflow until the double-quotes are removed from "main".  

<img width="1043" alt="Screen Shot 2022-06-09 at 4 03 24 PM" src="https://user-images.githubusercontent.com/25905289/172934502-73af4161-ae9e-4b63-b405-5b6b944aca34.png">

**Comment by bflad** [comment]
Hi @kjjames 👋 Thank you for reporting this. Those GitHub Actions starter workflow configurations are managed by GitHub maintainers, for example the Terraform one can be found here: https://github.com/actions/starter-workflows/blob/main/deployments/terraform.yml

Since this is not directly actionable in this repository, I'm going to close this issue, but I will reach out internally to see whether that starter workflow is desirable at all.
