### ISSUE TITLE
Error while installing hashicorp/alicloud v1.180.0: - string "1; mode=block": invalid

### ISSUE THREAD

**Issue by p24johnruiz** [hashicorp/setup-terraform#234]
Hello.
I was working fine with my tf scripts and github actions, but suddenly the following error start appearing since yesterday:

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/alicloud v1.180.0: could not query
│ provider registry for registry.terraform.io/hashicorp/alicloud: registry
│ response includes invalid version string "1; mode=block": invalid
│ characters "; mode=block"

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

The github actions script is like this:
   - uses: hashicorp/setup-terraform@v1

And the provider is:
  provider "alicloud" 

I have not changed anything and as I said, it suddenly starts showing an error.

**Comment by p24johnruiz** [comment]
Meantime, and as a workaroud, I modified the provider.tf file by adding this line <version = "=1.179.0">

**Comment by bflad** [comment]
Hi @p24johnruiz 👋 Thank you for reporting this and sorry you ran into trouble here. This appears to have been an issue with the Terraform Registry, which I'm guessing has long since been resolved. If you have future provider installation bug reports, you can submit those to https://github.com/hashicorp/terraform/issues, where Terraform maintainers will be looking for these types of reports, rather than this GitHub repository's issue tracker which is only intended for bug reports and feature requests with the `setup-terraform` GitHub Action itself.
