### ISSUE TITLE
Terraform init fails with "cookieAttributeList.unparsed"

### ISSUE THREAD

**Issue by fabri2000779** [hashicorp/setup-terraform#455]
Hello is there any regresion on this?
https://github.com/hashicorp/setup-terraform/issues/359

We are using the following:
Github Runner version: v2.321.0
Terraform Version: 1.10.2
We use AWS roles.
If you need more information feel free asking i just want to understand why are we getting now this problem.

The error we recieve:
<img width="799" alt="image" src="https://github.com/user-attachments/assets/07cdb053-6e94-4026-9208-7ff2a107d1b9" />

After switch in the setup to:
```
terraform_wrapper: false
```

it start working again.

**Comment by austinvalle** [comment]
Hey there @fabri2000779 👋🏻 , thanks for reporting the issue and sorry you're running into trouble here.

I don't believe there have been any changes prior to the latest release of this GH action that would cause this (last release was August this year) 🤔 

As you found, the `setup-terraform` action installs a nodejs wrapper by default, which will be executed when you run `terraform -chdir=int/ init`. This specific error looks like the version of node that ran the wrapper was something below `15.0.0`, since that's when the `??=` operator was introduced: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment#browser_compatibility

As for what version of nodejs will run the wrapper, that would be determined by the environment of the github action runner, via this shebang line here: https://github.com/hashicorp/setup-terraform/blob/344fef46b6edc7c46ce8b3b8b0a3ece7e77e05f0/wrapper/terraform.js#L1

I believe `#!/usr/bin/env node` will just find the first option in your $PATH that matches it, so it's possible that having multiple versions of node installed on your GitHub runner could cause the wrapper to run with an older version of NodeJS (thus producing this syntax error).

Do you have any other (older) versions of NodeJS installed on the github runner, like via `setup-node` or something similar?

**Comment by austinvalle** [comment]
I'm not sure if self hosted runners come with a pre-installed NodeJS version baked in, but the latest version of `setup-terraform` in general should be run with `node 20`

**Comment by austinvalle** [comment]
No worries, glad that fixed the issue! The wrapper in general is very subtle and can be the cause of a bunch of weird issues 🫤
